// GENERATED by scripts/sync-photos.mjs — do not edit by hand.
// Add or replace a file in public/photos/ and re-run the script.
import type { StaticImageData } from "next/image";
import cherries from "@/public/photos/cherries.jpg";
import farm from "@/public/photos/farm.jpg";
import highlands from "@/public/photos/highlands.jpg";
import drying from "@/public/photos/drying.jpg";
import parchment from "@/public/photos/parchment.jpg";
import greenbeans from "@/public/photos/greenbeans.jpg";
import farmers from "@/public/photos/farmers.jpg";
import port from "@/public/photos/port.jpg";

export type PhotoCredit = {
  author: string;
  licence: string;
  licenceUrl: string;
  source: string;
};

export type PhotoEntry = { src: StaticImageData; credit: PhotoCredit | null };

/** Every slot the design can place; only some are filled at any given time. */
export type PhotoSlot = "cherries" | "farm" | "highlands" | "drying" | "wetmill" | "parchment" | "greenbeans" | "sorting" | "cupping" | "farmers" | "warehouse" | "port";

const filled = {
  cherries: { src: cherries, credit: { author: "Kamweti wa Mutu", licence: "CC BY-SA 4.0", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Kenyan_farmers_sorting_coffee_cherries.jpg" } },
  farm: { src: farm, credit: { author: "Lebu Ayiga", licence: "CC BY 4.0", licenceUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Coffee_plantation_near_Kawaida_Falls,_Cianda,_Kiambu_County_01.jpg" } },
  highlands: { src: highlands, credit: { author: "John Spooner", licence: "CC BY 2.0", licenceUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Mount_Kenya_skyline.jpg" } },
  drying: { src: drying, credit: { author: "PHILIP ASEDRI DRADRIO", licence: "CC BY-SA 4.0", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Women_drying_coffee.jpg" } },
  parchment: { src: parchment, credit: { author: "Felipe Quijano", licence: "CC BY-SA 4.0", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Colombian_Parchment_Coffee.jpg" } },
  greenbeans: { src: greenbeans, credit: { author: "Isai Symens", licence: "CC BY-SA 4.0", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Coffee_beans_unroasted.jpg" } },
  farmers: { src: farmers, credit: { author: "Shirleen.Kay", licence: "CC BY-SA 4.0", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Small_Scale_Coffee_Farming_in_Kenya.jpg" } },
  port: { src: port, credit: { author: "Ian Kiptoo", licence: "CC BY 4.0", licenceUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Container_ship_exiting_Mombasa_port,_Kenya_01.jpg" } },
} satisfies Partial<Record<PhotoSlot, PhotoEntry>>;

export const photos: Partial<Record<PhotoSlot, PhotoEntry>> = filled;

/** Slots that actually have a file right now, in design order. */
export const filledSlots = Object.keys(filled) as PhotoSlot[];

export function photo(slot: PhotoSlot): PhotoEntry | undefined {
  return photos[slot];
}

/** Attribution for the credits block — only photos that require it. */
export const attributions = filledSlots
  .map((s) => ({ slot: s, ...(photos[s] as PhotoEntry) }))
  .filter((p) => p.credit !== null);
