// Regenerates lib/photos.ts from whatever currently sits in public/photos/.
// next/image needs literal static imports to derive width/height/blurDataURL,
// so the file cannot just read the directory at runtime.
//
// Drop a new photo in as public/photos/<slot>.jpg, run `node scripts/sync-photos.mjs`,
// and it becomes available as photos.<slot>.
import { readdir, writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.cwd();
const DIR = join(ROOT, "public", "photos");

// Every slot the site knows how to place. A slot with no file simply renders
// its illustrated fallback, so this list can run ahead of the photography.
const SLOTS = [
  "cherries", "farm", "highlands", "drying", "wetmill", "parchment",
  "greenbeans", "sorting", "cupping", "farmers", "warehouse", "port",
];

const files = (await readdir(DIR)).filter((f) => /\.(jpe?g|png|webp|avif)$/i.test(f));
const found = new Map();
for (const f of files) {
  const slot = f.replace(/\.[^.]+$/, "");
  if (SLOTS.includes(slot)) found.set(slot, f);
}

let credits = [];
try {
  credits = JSON.parse(await readFile(join(DIR, "credits.json"), "utf8"));
} catch {
  // credits.json is optional — own photography needs no attribution block.
}
const creditFor = new Map(credits.map((c) => [c.key, c]));

const present = SLOTS.filter((s) => found.has(s));
const imports = present
  .map((s) => `import ${s} from "@/public/photos/${found.get(s)}";`)
  .join("\n");

const entries = present
  .map((s) => {
    const c = creditFor.get(s);
    const credit = c
      ? `{ author: ${JSON.stringify(c.author)}, licence: ${JSON.stringify(c.licence)}, licenceUrl: ${JSON.stringify(c.licenceUrl ?? "")}, source: ${JSON.stringify(c.source)} }`
      : "null";
    return `  ${s}: { src: ${s}, credit: ${credit} },`;
  })
  .join("\n");

const out = `// GENERATED by scripts/sync-photos.mjs — do not edit by hand.
// Add or replace a file in public/photos/ and re-run the script.
import type { StaticImageData } from "next/image";
${imports}

export type PhotoCredit = {
  author: string;
  licence: string;
  licenceUrl: string;
  source: string;
};

export type PhotoEntry = { src: StaticImageData; credit: PhotoCredit | null };

/** Every slot the design can place; only some are filled at any given time. */
export type PhotoSlot = ${SLOTS.map((s) => `"${s}"`).join(" | ")};

const filled = {
${entries}
} satisfies Partial<Record<PhotoSlot, PhotoEntry>>;

export const photos: Partial<Record<PhotoSlot, PhotoEntry>> = filled;

/** Slots that actually have a file right now, in design order. */
export const filledSlots = Object.keys(filled) as PhotoSlot[];

export function photo(slot: PhotoSlot): PhotoEntry | undefined {
  return photos[slot];
}

/** Attribution for the credits block — only photos that require it. */
export const attributions = filledSlots
  .map((s) => ({ slot: s, ...(photos[s] as PhotoEntry) }))
  .filter((p) => p.credit !== null);
`;

await writeFile(join(ROOT, "lib", "photos.ts"), out);
console.log(
  `lib/photos.ts: ${present.length}/${SLOTS.length} slots filled -> ${present.join(", ")}`
);
const missing = SLOTS.filter((s) => !found.has(s));
if (missing.length) console.log(`empty (illustrated fallback): ${missing.join(", ")}`);
